version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "monthly" ,
 // Add the IDs of extensions you want installed when the container is created.
 "customizations": {
     "vscode": {
         "extensions": [
             "GitHub.copilot"
         ]
     },
     "codespaces": {
         "openFiles": [
             "codespace.md"
         ]
     }
 }
